---
language: python
sudo: required
cache:
  pip: true

env:
  global:
    - fast_finish: true

services:
  - docker

before_install:
  - sudo apt-get -qq update

install:
  - sudo apt-get -y install python-pip libssl-dev
  - pip install --upgrade setuptools
  - pip install molecule
  - pip install molecule[docker]

script:
  - cookiecutter https://github.com/jonsible/skeleton-build --no-input role_name=zsh
  - cd zsh
  - molecule create
  - molecule lint
  - molecule converge -- -e zsh_install_from_source=true
  - molecule destroy

notifications:
  email:
    on_failure: change
    on_success: never
