---
- name: Converge
  hosts: all
  vars:
    {{ cookiecutter.role_name }}_install_from_source: true
    {{ cookiecutter.role_name }}_user_strip: ['user.*']
    {{ cookiecutter.role_name }}_user_filter: ['jsch.*']
    {{ cookiecutter.role_name }}_source_path: "/opt"
    {{ cookiecutter.role_name }}_skel_config: true
    {{ cookiecutter.role_name }}_user_install: true
  pre_tasks:
    - name: Update cache
      apt:
        update_cache: true
      when: ansible_os_family == "Debian"
  tasks:
    - include_role:
        name: geerlingguy.git

    - name: Creating users
      become: true
      user:
        name: "{{'{{'}} item {{'}}'}}"
        shell: /bin/bash
      loop: ['jscherrer', 'user1', 'user2', 'svc_user', 'svc_user2']

    - include_role:
        name: {{ cookiecutter.role_name }}

    - include_role:
        name: {{ cookiecutter.role_name }}
        apply:
          tags:
            - molecule-idempotence-notest
      vars:
        {{ cookiecutter.role_name }}_force_install: true
      tags:
        - molecule-idempotence-notest
