---
- name: Installing build tools
  become: true
  pacman:
    name: "{{'{{'}} build_tools {{'}}'}}"
    update_cache: true
    state: present
  when: {{ cookiecutter.role_name }}_install_from_source|bool

- name: Installing additionnal build tools
  become: true
  apt:
    name: "{{'{{'}} item {{'}}'}}"
    state: present
  loop:
    - ncurses
    - libevent
  when: {{ cookiecutter.role_name }}_install_from_source|bool
