---
- name: Converge
  hosts: all
  vars:
    {{ cookiecutter.role_name }}_skel_config: true
  pre_tasks:
    - name: Update cache
      apt:
        update_cache: true
      when: ansible_os_family == "Debian"
  tasks:
    - include_role:
        name: geerlingguy.git

    - include_role:
        name: {{ cookiecutter.role_name }}
