---
- name: Converge
  hosts: all
  vars:
    {{ cookiecutter.role_name }}_skel_config: true
  tasks:
    - include_role:
        name: geerlingguy.git

    - include_role:
        name: {{ cookiecutter.role_name }}
