---
- name: Creating {{ cookiecutter.role_name }} versioned directory
  become: true
  file:
    path: "{{'{{'}} {{ cookiecutter.role_name }}_source_path {{'}}'}}/{{ cookiecutter.role_name }}-{{'{{'}} {{ cookiecutter.role_name }}_git_version {{'}}'}}/"
    state: directory
    mode: 0755

- name: Downloading the latest version of {{ cookiecutter.role_name }}
  become: true
  unarchive:
    src: "{{'{{'}} source_url {{'}}'}}"
    dest: "{{'{{'}} {{ cookiecutter.role_name }}_source_path {{'}}'}}/{{ cookiecutter.role_name }}-{{'{{'}} {{ cookiecutter.role_name }}_git_version {{'}}'}}/"
    extra_opts:
      - --strip-components=1
    remote_src: true

- name: Creating build directory
  become: true
  file:
    path: "{{'{{'}} {{ cookiecutter.role_name }}_source_path {{'}}'}}/{{ cookiecutter.role_name }}-{{'{{'}} {{ cookiecutter.role_name }}_git_version {{'}}'}}/build"
    state: directory
    mode: 0755

- name: Cmake {{ cookiecutter.role_name }}
  become: true
  shell: |
    scl enable devtoolset-8 -- ./configure
    # scl enable devtoolset-8 -- /usr/bin/cmake ..
  changed_when: false
  args:
    chdir: "{{'{{'}} {{ cookiecutter.role_name }}_source_path {{'}}'}}/{{ cookiecutter.role_name }}-{{'{{'}} {{ cookiecutter.role_name }}_git_version {{'}}'}}/build/"

- name: Making {{ cookiecutter.role_name }}
  become: true
  shell: |
    scl enable devtoolset-8 -- make
  changed_when: false
  args:
    chdir: "{{'{{'}} {{ cookiecutter.role_name }}_source_path {{'}}'}}/{{ cookiecutter.role_name }}-{{'{{'}} {{ cookiecutter.role_name }}_git_version {{'}}'}}"

- name: Installing {{ cookiecutter.role_name }}
  become: true
  make:
    chdir: "{{'{{'}} {{ cookiecutter.role_name }}_source_path {{'}}'}}/{{ cookiecutter.role_name }}-{{'{{'}} {{ cookiecutter.role_name }}_git_version {{'}}'}}"
    target: install
    params:
      PREFIX: "{{'{{'}} prefix {{'}}'}}"
  when: not {{ cookiecutter.role_name }}_user_install|bool

- name: Installing {{ cookiecutter.role_name }} (user)
  become: true
  become_user: "{{'{{'}} item.key {{'}}'}}"
  make:
    chdir: "{{'{{'}} {{ cookiecutter.role_name }}_source_path {{'}}'}}/{{ cookiecutter.role_name }}-{{'{{'}} {{ cookiecutter.role_name }}_git_version {{'}}'}}"
    target: install
    params:
      PREFIX: "{{'{{'}} item.value['home'] {{'}}'}}/.local/bin"
  when: {{ cookiecutter.role_name }}_user_install|bool
  loop: "{{'{{'}} lookup('dict', {{ cookiecutter.role_name }}_user_list) {{'}}'}}"
