---
- name: Creating {{ cookiecutter.role_name }} versioned directory
  become: true
  file:
    path: "{{'{{'}} {{ cookiecutter.role_name }}_source_path {{'}}'}}/{{ cookiecutter.role_name }}-{{'{{'}} {{ cookiecutter.role_name }}_git_version {{'}}'}}/"
    state: directory
    mode: 0755
  when: not {{ cookiecutter.role_name }}_user_install|bool

- name: Downloading the latest version of {{ cookiecutter.role_name }}
  become: true
  unarchive:
    src: "{{'{{'}} {{ cookiecutter.role_name }}_source_url {{'}}'}}"
    dest: "{{'{{'}} {{ cookiecutter.role_name }}_source_path {{'}}'}}/{{ cookiecutter.role_name }}-{{'{{'}} {{ cookiecutter.role_name }}_git_version {{'}}'}}/"
    extra_opts:
      - --strip-components=1
    remote_src: true
  when: not {{ cookiecutter.role_name }}_user_install|bool

- name: Configuring {{ cookiecutter.role_name }}
  become: true
  shell: |
    ./configure --prefix="{{'{{'}} {{ cookiecutter.role_name }}_prefix {{'}}'}}"
  changed_when: false
  args:
    chdir: "{{'{{'}} {{ cookiecutter.role_name }}_source_path {{'}}'}}/{{ cookiecutter.role_name }}-{{'{{'}} {{ cookiecutter.role_name }}_git_version {{'}}'}}/"
  when: not {{ cookiecutter.role_name }}_user_install|bool

- name: Making {{ cookiecutter.role_name }}
  become: true
  make:
    chdir: "{{'{{'}} {{ cookiecutter.role_name }}_source_path {{'}}'}}/{{ cookiecutter.role_name }}-{{'{{'}} {{ cookiecutter.role_name }}_git_version {{'}}'}}"
  when: not {{ cookiecutter.role_name }}_user_install|bool

- name: Installing {{ cookiecutter.role_name }}
  become: true
  make:
    chdir: "{{'{{'}} {{ cookiecutter.role_name }}_source_path {{'}}'}}/{{ cookiecutter.role_name }}-{{'{{'}} {{ cookiecutter.role_name }}_git_version {{'}}'}}"
    target: install
    params:
      PREFIX: "{{'{{'}} {{ cookiecutter.role_name }}_prefix {{'}}'}}"
  when: not {{ cookiecutter.role_name }}_user_install|bool

- name: Include {{ cookiecutter.role_name }} user install
  include_tasks: install_source_user.yml
  when: {{ cookiecutter.role_name }}_user_install|bool
  loop: "{{'{{'}} lookup('dict', {{ cookiecutter.role_name }}_user_list, wantlist=true) {{'}}'}}"