---
- name: Creating {{ cookiecutter.role_name }} versioned directory
  become: true
  become_user: "{{'{{'}} item.key {{'}}'}}"
  file:
    path: "{{'{{'}} item.value['home'] {{'}}'}}/.local/src/{{ cookiecutter.role_name }}-{{'{{'}} {{ cookiecutter.role_name }}_git_version {{'}}'}}/"
    state: directory
    mode: 0755

- name: Downloading the latest version of {{ cookiecutter.role_name }}
  become: true
  become_user: "{{'{{'}} item.key {{'}}'}}"
  unarchive:
    src: "{{'{{'}} {{ cookiecutter.role_name }}_source_url {{'}}'}}"
    dest: "{{'{{'}} item.value['home'] {{'}}'}}/.local/src/{{ cookiecutter.role_name }}-{{'{{'}} {{ cookiecutter.role_name }}_git_version {{'}}'}}/"
    extra_opts:
      - --strip-components=1
    remote_src: true

- name: Configuring {{ cookiecutter.role_name }}
  become: true
  become_user: "{{'{{'}} item.key {{'}}'}}"
  shell: |
    ./configure --prefix="{{'{{'}} item.value['home'] {{'}}'}}/.local/"
  changed_when: false
  args:
    chdir: "{{'{{'}} item.value['home'] {{'}}'}}/.local/src/{{ cookiecutter.role_name }}-{{'{{'}} {{ cookiecutter.role_name }}_git_version {{'}}'}}/"

- name: Making {{ cookiecutter.role_name }}
  become: true
  make:
    chdir: "{{'{{'}} item.value['home'] {{'}}'}}/.local/src/{{ cookiecutter.role_name }}-{{'{{'}} {{ cookiecutter.role_name }}_git_version {{'}}'}}/"

- name: Installing {{ cookiecutter.role_name }} (user)
  become: true
  become_user: "{{'{{'}} item.key {{'}}'}}"
  changed_when: false
  make:
    chdir: "{{'{{'}} item.value['home'] {{'}}'}}/.local/src/{{ cookiecutter.role_name }}-{{'{{'}} {{ cookiecutter.role_name }}_git_version {{'}}'}}/"
    target: install
    params:
      PREFIX: "{{'{{'}} item.value['home'] {{'}}'}}/.local/"
