---
- name: Uninstalling {{ cookiecutter.role_name }}
  become: true
  make:
    target: uninstall
    chdir: "{{'{{'}} {{ cookiecutter.role_name }}_source_path {{'}}'}}/{{ cookiecutter.role_name }}-{{'{{'}} {{ cookiecutter.role_name }}_local_version {{'}}'}}/"
  when: not {{ cookiecutter.role_name }}_user_install|bool

- name: Uninstalling {{ cookiecutter.role_name }} (user)
  become: true
  become_user: "{{'{{'}} item.key {{'}}'}}"
  make:
    target: uninstall
    chdir: "{{'{{'}} {{ cookiecutter.role_name }}_source_path {{'}}'}}/{{ cookiecutter.role_name }}-{{'{{'}} {{ cookiecutter.role_name }}_local_version {{'}}'}}/"
  when: {{ cookiecutter.role_name }}_user_install|bool

- name: Removing source folder
  become: true
  file:
    path: "{{'{{'}} {{ cookiecutter.role_name }}_source_path {{'}}'}}/{{ cookiecutter.role_name }}-{{'{{'}} {{ cookiecutter.role_name }}_local_version {{'}}'}}/"
    state: absent
